# Generated by Django 4.0.6 on 2022-08-07 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.IntegerField(default=uuid.UUID('5045267c-8f87-491b-baff-ecb010f029f5')),
        ),
    ]
