# Generated by Django 4.0.6 on 2022-08-07 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.IntegerField(default=uuid.UUID('7fafc84c-1827-4e00-94bf-061142d58929')),
        ),
    ]
