# Generated by Django 4.0.6 on 2022-08-08 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.IntegerField(default=uuid.UUID('be90f81a-5bfe-465c-8602-4e6dde6b4b1e')),
        ),
    ]
