# Generated by Django 4.0.6 on 2022-08-08 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.IntegerField(default=uuid.UUID('bfba1e6e-f1d8-43d5-a5a7-ff17e29c8ba4')),
        ),
    ]
