# Generated by Django 4.0.6 on 2022-08-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_profile_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uid',
        ),
    ]
